### PR TITLE
Added combineLatest3, combineLatest4, combineLatest5 and combineLatest6

### PR DESCRIPTION
**Pull request by SAGARSURI**
Hey @escamoteur 
I have added `combineLatest` variants extension methods. Please have a look at the PR.

### CODE REVIEW

**Comment by escamoteur** [comment]
Hi, 
cool. please pull the latest state from this morning because I discovered a serious bug which is now addressed, which will also affect your new classes

**Comment by SAGARSURI** [comment]
merged the latest changes.

**Comment by SAGARSURI** [comment]
Hey @escamoteur 
Can you go through the PR once you get the time? 😃

**Comment by escamoteur** [comment]
Hi,

please check the latest commits I made to the repo. I was missing an important scenario where a chain of operators could loose there subscriptotions which let me to add an init() function that is called if necessary in `addListener`.

**Comment by escamoteur** [comment]
which I myself actually forgot to add to the basic `combineLatest` method because it doesn't extend from `FunctionalValueNotifier` as the other functions. 
Could you update all combineLatest to care for the resubscribing?

**Comment by SAGARSURI** [comment]
Yeah sure. Even I was thinking when you said my changes will also impact. But it didn't. I will make those relevant changes.

**Comment by SAGARSURI** [comment]
Hey @escamoteur 
I applied the changes which you added to `FunctionalValueNotifier` i.e creating `init` method and call it in the `addListener` method. But when I tried the unsubscribe/resubscribe scenario in the test for `combineLatest3`. I didn't see the bug being reproduced. 

Please see my last commit with the changes. You will see only `combineLatest` behaving weirdly with the changes. But the other variants work perfectly. 

I have commented the `init()` call in the `addListener` for `combineLatest3` variant and the test case still pass even I unsubscribe and resubscribe.

**Comment by SAGARSURI** [comment]
Or am I doing something wrong?

**Comment by escamoteur** [comment]
Sorry that it took me that long. I think I found the problem. will fix it with the version I will push in a moment

**Comment by SAGARSURI** [comment]
No problem 😉. I hope you had a good rest during this gap.

**Comment by SAGARSURI** [comment]
Also please look at CombineLatest3 because for some experimentation I commented the init() function. So please have a look at that.

**Pull request merged**
